# Generated by Django 5.2 on 2025-04-13 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('farming_type', models.CharField(choices=[('dairy', 'Dairy'), ('meat', 'Meat'), ('both', 'Both Dairy and Meat')], default='both', max_length=20, verbose_name='farming type')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
            ],
            options={
                'verbose_name': 'animal type',
                'verbose_name_plural': 'animal types',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='name')),
                ('description', models.TextField(blank=True, verbose_name='description')),
                ('average_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='average weight (kg)')),
                ('average_height', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='average height (cm)')),
                ('average_milk_production', models.DecimalField(blank=True, decimal_places=2, help_text='Average milk production per day for dairy animals', max_digits=8, null=True, verbose_name='average milk production (liters/day)')),
                ('lactation_period', models.IntegerField(blank=True, help_text='Average lactation period in days', null=True, verbose_name='lactation period (days)')),
                ('average_meat_yield', models.DecimalField(blank=True, decimal_places=2, help_text='Average meat yield per animal', max_digits=8, null=True, verbose_name='average meat yield (kg)')),
                ('growth_rate', models.DecimalField(blank=True, decimal_places=2, help_text='Average weight gain per month', max_digits=6, null=True, verbose_name='growth rate (kg/month)')),
                ('gestation_period', models.IntegerField(blank=True, help_text='Average gestation period in days', null=True, verbose_name='gestation period (days)')),
                ('maturity_age', models.IntegerField(blank=True, help_text='Age at which the animal reaches maturity in months', null=True, verbose_name='maturity age (months)')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('animal_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='breeds', to='ezanimal.animaltype', verbose_name='animal type')),
            ],
            options={
                'verbose_name': 'breed',
                'verbose_name_plural': 'breeds',
                'ordering': ['animal_type', 'name'],
                'unique_together': {('animal_type', 'name')},
            },
        ),
    ]
