# Generated by Django 5.2 on 2025-04-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ezanimal', '0001_initial'),
        ('ezcore', '0001_initial'),
        ('ezdairy', '0001_initial'),
        ('ezmeat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='animalhealth',
            name='dairy_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ezdairy.dairyanimal', verbose_name='dairy animal'),
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='meat_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='ezmeat.meatanimal', verbose_name='meat animal'),
        ),
        migrations.AddField(
            model_name='animalhealth',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_health_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='expense',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expenses', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='expense',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_expenses', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='dairy_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='ezdairy.dairyanimal', verbose_name='dairy animal'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='meat_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='feeding_records', to='ezmeat.meatanimal', verbose_name='meat animal'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_feedings', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='animal_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_schedules', to='ezanimal.animaltype', verbose_name='animal type'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='breed',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_schedules', to='ezanimal.breed', verbose_name='breed'),
        ),
        migrations.AddField(
            model_name='feedingschedule',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_feeding_schedules', to=settings.AUTH_USER_MODEL, verbose_name='created by'),
        ),
        migrations.AddField(
            model_name='feedingscheduleitem',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ezcore.feedingschedule', verbose_name='schedule'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='schedule_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='feeding_records', to='ezcore.feedingscheduleitem', verbose_name='schedule item'),
        ),
        migrations.AddField(
            model_name='feedingscheduleitem',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule_items', to='ezcore.feedtype', verbose_name='feed type'),
        ),
        migrations.AddField(
            model_name='feedingrecord',
            name='feed_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='feeding_records', to='ezcore.feedtype', verbose_name='feed type'),
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inventory_items', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='ezcore.inventoryitem', verbose_name='item'),
        ),
        migrations.AddField(
            model_name='inventorytransaction',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_inventory_transactions', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='sale',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sales', to=settings.AUTH_USER_MODEL, verbose_name='owner'),
        ),
        migrations.AddField(
            model_name='sale',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_sales', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AddField(
            model_name='saleitem',
            name='sale',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='ezcore.sale', verbose_name='sale'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='dairy_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='ezdairy.dairyanimal', verbose_name='dairy animal'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='meat_animal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vaccinations', to='ezmeat.meatanimal', verbose_name='meat animal'),
        ),
        migrations.AddField(
            model_name='vaccination',
            name='recorded_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_vaccinations', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
    ]
