# Generated by Django 5.2 on 2025-04-13 10:50

import django.db.models.deletion
import ezcore.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezcore', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
                ('objects', ezcore.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_animals',
            field=models.BooleanField(default=False, verbose_name='can manage animals'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_employees',
            field=models.BooleanField(default=False, verbose_name='can manage employees'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_feeding',
            field=models.BooleanField(default=False, verbose_name='can manage feeding'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_health',
            field=models.BooleanField(default=False, verbose_name='can manage health records'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_inventory',
            field=models.BooleanField(default=False, verbose_name='can manage inventory'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_manage_sales',
            field=models.BooleanField(default=False, verbose_name='can manage sales'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_view_reports',
            field=models.BooleanField(default=False, verbose_name='can view reports'),
        ),
        migrations.AddField(
            model_name='user',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='contact number'),
        ),
        migrations.AddField(
            model_name='user',
            name='employer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='employees', to=settings.AUTH_USER_MODEL, verbose_name='employer'),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True, verbose_name='hire date'),
        ),
        migrations.AddField(
            model_name='user',
            name='is_farm_owner',
            field=models.BooleanField(default=True, verbose_name='farm owner status'),
        ),
        migrations.AddField(
            model_name='user',
            name='job_title',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='job title'),
        ),
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('owner', 'Farm Owner'), ('manager', 'Farm Manager'), ('veterinarian', 'Veterinarian'), ('worker', 'Farm Worker'), ('accountant', 'Accountant')], default='owner', max_length=50, verbose_name='role'),
        ),
        migrations.AlterField(
            model_name='user',
            name='farm_location',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='farm location'),
        ),
        migrations.AlterField(
            model_name='user',
            name='farm_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='farm name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='farm_size',
            field=models.FloatField(blank=True, null=True, verbose_name='farm size (acres)'),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=150, verbose_name='first name'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=150, verbose_name='last name'),
        ),
    ]
