# Generated by Django 5.2 on 2025-04-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ezanimal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DairyAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='tag number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male')], default='female', max_length=10, verbose_name='gender')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='weight (kg)')),
                ('acquisition_date', models.DateField(verbose_name='acquisition date')),
                ('acquisition_type', models.CharField(choices=[('born', 'Born on farm'), ('purchased', 'Purchased'), ('gifted', 'Gifted'), ('other', 'Other')], default='purchased', max_length=20, verbose_name='acquisition type')),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='acquisition cost')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('lactating', 'Lactating'), ('dry', 'Dry'), ('pregnant', 'Pregnant'), ('calf', 'Calf'), ('heifer', 'Heifer'), ('bull', 'Bull'), ('sold', 'Sold'), ('deceased', 'Deceased'), ('other', 'Other')], default='lactating', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal_type', models.ForeignKey(limit_choices_to=models.Q(('farming_type', 'dairy'), ('farming_type', 'both'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='dairy_animals', to='ezanimal.animaltype', verbose_name='animal type')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dairy_animals', to='ezanimal.breed', verbose_name='breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dairy_animals', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'dairy animal',
                'verbose_name_plural': 'dairy animals',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='Lactation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lactation_number', models.PositiveIntegerField(verbose_name='lactation number')),
                ('start_date', models.DateField(verbose_name='start date')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='end date')),
                ('calving_date', models.DateField(verbose_name='calving date')),
                ('total_production', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total production (liters)')),
                ('peak_production', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='peak production (liters/day)')),
                ('peak_date', models.DateField(blank=True, null=True, verbose_name='peak date')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lactations', to='ezdairy.dairyanimal', verbose_name='animal')),
                ('calf', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='born_in_lactation', to='ezdairy.dairyanimal', verbose_name='calf')),
            ],
            options={
                'verbose_name': 'lactation',
                'verbose_name_plural': 'lactations',
                'ordering': ['animal', '-lactation_number'],
                'unique_together': {('animal', 'lactation_number')},
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('morning_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='morning amount (liters)')),
                ('evening_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='evening amount (liters)')),
                ('additional_amount', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='additional amount (liters)')),
                ('fat_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='fat percentage')),
                ('protein_percentage', models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='protein percentage')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='milk_records', to='ezdairy.dairyanimal', verbose_name='animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_milk_productions', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'milk production',
                'verbose_name_plural': 'milk productions',
                'ordering': ['-date', 'animal'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
