# Generated by Django 5.2 on 2025-05-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezanimal', '0001_initial'),
        ('ezdairy', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lactation',
            options={'ordering': ['-start_date'], 'verbose_name': 'lactation', 'verbose_name_plural': 'lactations'},
        ),
        migrations.AlterModelOptions(
            name='milkproduction',
            options={'ordering': ['-date'], 'verbose_name': 'milk production', 'verbose_name_plural': 'milk productions'},
        ),
        migrations.RemoveField(
            model_name='dairyanimal',
            name='acquisition_cost',
        ),
        migrations.RemoveField(
            model_name='dairyanimal',
            name='acquisition_type',
        ),
        migrations.RemoveField(
            model_name='dairyanimal',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='lactation',
            name='calf',
        ),
        migrations.RemoveField(
            model_name='lactation',
            name='calving_date',
        ),
        migrations.RemoveField(
            model_name='milkproduction',
            name='additional_amount',
        ),
        migrations.RemoveField(
            model_name='milkproduction',
            name='fat_percentage',
        ),
        migrations.RemoveField(
            model_name='milkproduction',
            name='protein_percentage',
        ),
        migrations.AddField(
            model_name='dairyanimal',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='acquisition price'),
        ),
        migrations.AddField(
            model_name='dairyanimal',
            name='breed_avg_milk_production',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='breed average milk production (liters/day)'),
        ),
        migrations.AddField(
            model_name='dairyanimal',
            name='father_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='father tag'),
        ),
        migrations.AddField(
            model_name='dairyanimal',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='ezdairy.dairyanimal', verbose_name='mother'),
        ),
        migrations.AddField(
            model_name='dairyanimal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='lactation',
            name='expected_duration_days',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='expected duration (days)'),
        ),
        migrations.AddField(
            model_name='lactation',
            name='expected_peak_production',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected peak production (liters/day)'),
        ),
        migrations.AddField(
            model_name='lactation',
            name='expected_total_production',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='expected total production (liters)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='expected_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected amount (liters)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='expected_next_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected daily amount next month (liters)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='expected_next_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected daily amount next week (liters)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='fat_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='fat content (%)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='protein_content',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='protein content (%)'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='time_of_day',
            field=models.CharField(choices=[('morning', 'Morning'), ('evening', 'Evening'), ('both', 'Both')], default='both', max_length=10, verbose_name='time of day'),
        ),
        migrations.AddField(
            model_name='milkproduction',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=6, verbose_name='total amount (liters)'),
        ),
        migrations.AlterField(
            model_name='dairyanimal',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='acquisition date'),
        ),
        migrations.AlterField(
            model_name='dairyanimal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dairy_animals', to='ezanimal.animaltype', verbose_name='animal type'),
        ),
        migrations.AlterField(
            model_name='dairyanimal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='dairyanimal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='dairyanimal',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('dry', 'Dry'), ('pregnant', 'Pregnant'), ('sold', 'Sold'), ('deceased', 'Deceased')], default='active', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='lactation',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='milkproduction',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_milk_productions', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
    ]
