# Generated by Django 5.2 on 2025-04-13 10:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ezanimal', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MeatAnimal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(max_length=50, unique=True, verbose_name='tag number')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='name')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='date of birth')),
                ('gender', models.CharField(choices=[('female', 'Female'), ('male', 'Male'), ('castrated', 'Castrated Male')], max_length=10, verbose_name='gender')),
                ('initial_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='initial weight (kg)')),
                ('current_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='current weight (kg)')),
                ('acquisition_date', models.DateField(verbose_name='acquisition date')),
                ('acquisition_type', models.CharField(choices=[('born', 'Born on farm'), ('purchased', 'Purchased'), ('gifted', 'Gifted'), ('other', 'Other')], default='purchased', max_length=20, verbose_name='acquisition type')),
                ('acquisition_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='acquisition cost')),
                ('target_weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='target weight (kg)')),
                ('expected_finish_date', models.DateField(blank=True, null=True, verbose_name='expected finish date')),
                ('is_active', models.BooleanField(default=True, verbose_name='active')),
                ('status', models.CharField(choices=[('growing', 'Growing'), ('finishing', 'Finishing'), ('ready', 'Ready for slaughter'), ('breeding', 'Breeding stock'), ('sold', 'Sold'), ('slaughtered', 'Slaughtered'), ('deceased', 'Deceased'), ('other', 'Other')], default='growing', max_length=20, verbose_name='status')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal_type', models.ForeignKey(limit_choices_to=models.Q(('farming_type', 'meat'), ('farming_type', 'both'), _connector='OR'), on_delete=django.db.models.deletion.PROTECT, related_name='meat_animals', to='ezanimal.animaltype', verbose_name='animal type')),
                ('breed', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_animals', to='ezanimal.breed', verbose_name='breed')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meat_animals', to=settings.AUTH_USER_MODEL, verbose_name='owner')),
            ],
            options={
                'verbose_name': 'meat animal',
                'verbose_name_plural': 'meat animals',
                'ordering': ['tag_number'],
            },
        ),
        migrations.CreateModel(
            name='SlaughterRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slaughter_date', models.DateField(verbose_name='slaughter date')),
                ('live_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='live weight (kg)')),
                ('carcass_weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='carcass weight (kg)')),
                ('dressing_percentage', models.DecimalField(blank=True, decimal_places=2, help_text='Carcass weight as a percentage of live weight', max_digits=5, null=True, verbose_name='dressing percentage')),
                ('quality_grade', models.CharField(blank=True, choices=[('prime', 'Prime'), ('choice', 'Choice'), ('select', 'Select'), ('standard', 'Standard'), ('other', 'Other')], max_length=20, verbose_name='quality grade')),
                ('slaughter_location', models.CharField(blank=True, max_length=255, verbose_name='slaughter location')),
                ('processor', models.CharField(blank=True, max_length=255, verbose_name='processor')),
                ('processing_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='processing cost')),
                ('total_revenue', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='total revenue')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='slaughter_record', to='ezmeat.meatanimal', verbose_name='animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_slaughter_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'slaughter record',
                'verbose_name_plural': 'slaughter records',
                'ordering': ['-slaughter_date'],
            },
        ),
        migrations.CreateModel(
            name='WeightRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('weight', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='weight (kg)')),
                ('notes', models.TextField(blank=True, verbose_name='notes')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('animal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='weight_records', to='ezmeat.meatanimal', verbose_name='animal')),
                ('recorded_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_weight_records', to=settings.AUTH_USER_MODEL, verbose_name='recorded by')),
            ],
            options={
                'verbose_name': 'weight record',
                'verbose_name_plural': 'weight records',
                'ordering': ['-date', 'animal'],
                'unique_together': {('animal', 'date')},
            },
        ),
    ]
