# Generated by Django 5.2 on 2025-05-02 12:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezanimal', '0001_initial'),
        ('ezmeat', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weightrecord',
            options={'ordering': ['-date'], 'verbose_name': 'weight record', 'verbose_name_plural': 'weight records'},
        ),
        migrations.RemoveField(
            model_name='meatanimal',
            name='acquisition_cost',
        ),
        migrations.RemoveField(
            model_name='meatanimal',
            name='acquisition_type',
        ),
        migrations.RemoveField(
            model_name='meatanimal',
            name='expected_finish_date',
        ),
        migrations.RemoveField(
            model_name='meatanimal',
            name='initial_weight',
        ),
        migrations.RemoveField(
            model_name='slaughterrecord',
            name='processing_cost',
        ),
        migrations.RemoveField(
            model_name='slaughterrecord',
            name='total_revenue',
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='acquisition_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='acquisition price'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='acquisition_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='acquisition weight (kg)'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='breed_avg_daily_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='breed average daily gain (kg/day)'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='breed_avg_days_to_finish',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='breed average days to finish'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='breed_avg_finishing_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='breed average finishing weight (kg)'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='father_tag',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='father tag'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='mother',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offspring', to='ezmeat.meatanimal', verbose_name='mother'),
        ),
        migrations.AddField(
            model_name='meatanimal',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='expected_carcass_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected carcass weight (kg)'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='expected_dressing_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='expected dressing percentage'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='expected_live_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected live weight (kg)'),
        ),
        migrations.AddField(
            model_name='slaughterrecord',
            name='yield_grade',
            field=models.CharField(blank=True, max_length=10, null=True, verbose_name='yield grade'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='expected_daily_gain',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=4, null=True, verbose_name='expected daily gain (kg/day)'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='expected_next_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected weight next month (kg)'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='expected_next_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected weight next week (kg)'),
        ),
        migrations.AddField(
            model_name='weightrecord',
            name='expected_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='expected weight (kg)'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='acquisition_date',
            field=models.DateField(blank=True, null=True, verbose_name='acquisition date'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='animal_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meat_animals', to='ezanimal.animaltype', verbose_name='animal type'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='current_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='current weight (kg)'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='is active'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='name'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='status',
            field=models.CharField(choices=[('growing', 'Growing'), ('finishing', 'Finishing'), ('ready', 'Ready for Slaughter'), ('sold', 'Sold'), ('slaughtered', 'Slaughtered'), ('deceased', 'Deceased')], default='growing', max_length=20, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='meatanimal',
            name='target_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='target weight (kg)'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='carcass_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='carcass weight (kg)'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='dressing_percentage',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=5, verbose_name='dressing percentage'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='live_weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='live weight (kg)'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='processor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='processor'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='quality_grade',
            field=models.CharField(blank=True, choices=[('prime', 'Prime'), ('choice', 'Choice'), ('select', 'Select'), ('standard', 'Standard'), ('commercial', 'Commercial'), ('utility', 'Utility')], max_length=20, null=True, verbose_name='quality grade'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_slaughters', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AlterField(
            model_name='slaughterrecord',
            name='slaughter_location',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='slaughter location'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='notes'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recorded_weights', to=settings.AUTH_USER_MODEL, verbose_name='recorded by'),
        ),
        migrations.AlterField(
            model_name='weightrecord',
            name='weight',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='weight (kg)'),
        ),
    ]
