# Generated by Django 5.2 on 2025-05-02 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ezmeat', '0002_alter_weightrecord_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slaughterrecord',
            name='dressing_percentage',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=5, verbose_name='dressing percentage'),
        ),
    ]
